### ISSUE TITLE
Graph not updating and average values remains the same because dataset contains two values when it should contain 360...

### ISSUE THREAD

**Issue by trekr5** [edasque/dashing-graphite-text-widget#3]
Hello,

Please see this gist as I'm unable to correctly format the code here.

https://gist.github.com/trekr5/443153c50cbe0480eb72

Can you please tell me what I'm doing wrong?
 
At the moment the graph is showing 7 donations with two elements in the dataset; one element is 9 and the other is 5 which strikes me as wrong.

**Comment by edasque** [comment]
Does the data come from statsd?
Can you attach a screenshot of what you see and a copy of the server output?
Can you clarify "At the moment the graph is showing 7 donations with two elements in the dataset; one element is 9 and the other is 5 which strikes me as wrong"?

**Comment by edasque** [comment]
No answer, closing.
